---
title: "Personal_project_PRS_Asthma"
author: "Heeduk Oh"
date: "`r Sys.Date()`"
output: html_document
---

## Import data

```{r}
prs <- read.table("./GWASsummarystats/Asthma_Demenais-et-al/PRS_results/1kgp_allchr_asthmaPRS.profile", header=TRUE)

head(prs)
tail(prs)

dim(prs)
```

```{r}
pop_info <- read.table("./1KGP/integrated_call_samples_v3.20130502.ALL.panel", header=TRUE)
head(pop_info)

geno_pop <- merge(prs, pop_info, by.x="IID", by.y="sample")
head(geno_pop)
tail(geno_pop)
```

## Plot histogram of PRS scores

```{r}
hist(geno_pop$SCORESUM, breaks=50, main="PRS Score Distribution for Asthma (1000 Genomes)", xlab="PRS Score")
```

## Summary of PRS scores

```{r}
summary(geno_pop$SCORESUM)
```

## Top 5% PRS scores

```{r}
# reorder by SCORESUM
geno_pop <- geno_pop[order(geno_pop$SCORESUM, decreasing=TRUE),]

# population of top 5%
table(head(geno_pop, n=ceiling(nrow(geno_pop)*0.05))$super_pop)
```

## ANOVA to compare PRS scores between populations

```{r}
# Run one-way ANOVA
aov_model <- aov(SCORESUM ~ super_pop, data = geno_pop)

# Get the summary of the ANOVA model (shows F-statistic and p-value)
summary(aov_model)
```

### Ad-hoc Tukey's Honest Significant Difference test

```{r}
# Perform Tukey's Honest Significant Difference test
tukey_results <- TukeyHSD(aov_model)
print(tukey_results)

```

### Plot distribution of PRS scores by population

```{r}
# import the Tukey test results saved in an excel sheet
library(readxl)
stat.test <- read_excel("./PRS-asthma_stat_test_used_for_plotting_sig_diff_in_R.xlsx", sheet = "Sheet1") # excel made manually

# plot
library(ggplot2)
library(ggpubr)
ggplot(geno_pop, aes(x=super_pop, y=SCORESUM, fill=super_pop)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", remove.bracket=F, size=2.5, tip.length=0.01, linetype=1, vjust="vjust", bracket.shorten = 0.05, color = "black")+
  labs(title="PRS Scores by 1000 Genomes Population", x="Population", y="PRS Score") +
  theme(legend.position = "none")

# save as png
png("./Images/PRS_scores_by_1000_Genomes_population.png", width=6, height=4, units = "in", res = 300)
ggplot(geno_pop, aes(x=super_pop, y=SCORESUM, fill=super_pop)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  labs(x="Population", y="PRS Score") +
  theme(legend.position = "none")
dev.off()

# save as png with the significant difference labels
png("./Images/PRS_scores_by_1000_Genomes_population_with_sigdiff.png", width=6, height=4, units = "in", res = 300)
ggplot(geno_pop, aes(x=super_pop, y=SCORESUM, fill=super_pop)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", remove.bracket=F, size=2.5, tip.length=0.01, linetype=1, vjust="vjust", bracket.shorten = 0.05, color = "black")+
  labs(x="Population", y="PRS Score") +
  theme(legend.position = "none")
dev.off()
```

## ANOVA to compare PRS scores between genders

```{r}
# Run one-way ANOVA
aov_model <- aov(SCORESUM ~ gender, data = geno_pop)

# Get the summary of the ANOVA model (shows F-statistic and p-value)
summary(aov_model)
```

### Plot distribution by gender

```{r}
# import the Tukey test results saved in an excel sheet
library(readxl)
stat.test <- read_excel("./PRS-asthma_stat_test_used_for_plotting_sig_diff_in_R.xlsx", sheet = "Sheet2") # excel made manually

# plot
ggplot(geno_pop, aes(x=gender, y=SCORESUM, fill=gender)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", remove.bracket=F, size=2.5, tip.length=0.01, linetype=1, vjust="vjust", bracket.shorten = 0.05, color = "black")+
  labs(title="PRS Scores by Gender", x="Gender", y="PRS Score") +
  theme(legend.position = "none")

# save as png
png("./Images/PRS_scores_by_gender.png", width=4, height=4, units = "in", res = 300)
ggplot(geno_pop, aes(x=gender, y=SCORESUM, fill=gender)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  labs(x="Gender", y="PRS Score") +
  theme(legend.position = "none")
dev.off()

# save as png with the significant difference labels
png("./Images/PRS_scores_by_gender_with_sigdiff.png", width=4, height=4, units = "in", res = 300)
ggplot(geno_pop, aes(x=gender, y=SCORESUM, fill=gender)) +
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") +
  theme_minimal() +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", remove.bracket=F, size=2.5, tip.length=0.01, linetype=1, vjust="vjust", bracket.shorten = 0.05, color = "black")+
  labs(x="Gender", y="PRS Score") +
  theme(legend.position = "none")
dev.off()
```
